edition = "2021"

newline_style = "Unix"
reorder_imports = false
match_block_trailing_comma = true

max_width = 132

struct_lit_width = 0	# never collapse struct literals

#use_small_heuristics = "Max"
#fn_call_width=132
#attr_fn_like_width=100
#struct_variant_width=35
#array_width=132
#chain_width=60
#single_line_if_else_max_width=50


## Experimental Features
unstable_features = true
blank_lines_upper_bound = 3
overflow_delimited_expr = true

# need to be able to align const equals
# need to not erase whitespace between end of line and comment
